version: '2.1'

services:
  db:
    hostname: postgres
    image: postgres:bullseye
    command: postgres -c 'max_connections=200'
    container_name: postgres
    restart: always
    # The PGUSER environment variable is required by the healthcheck test.
    environment:
      - POSTGRES_DB=washington
      - PGUSER=washington
      - POSTGRES_USER=washington
      - POSTGRES_PASSWORD=washington
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready"
      interval: 5s
      timeout: 10s
      retries: 3

  backend:
    build: .
    mem_limit: 300m
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ENVIRONMENT=dev
    restart: always
    ports:
      - "3510:3500"

  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - "3570:9090"
    volumes:
      - ./monitoring:/etc/prometheus/
    links:
      - backend

  grafana:
    image: grafana/grafana-oss:9.3.6
    ports:
      - "3000:3000"
    user: "472"
    volumes:
      - ./monitoring/grafana:/var/lib/grafana
    links:
      - backend
      - prometheus
